# Dynmap-GriefPrevention configuration
#
update:
  # Seconds between checks for claim updates
  period: 300

layer:
  name: "GriefPrevention"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 0
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0
  
# Set true to show 3D volumes for zones  
use3dregions: false

# Format for popup - substitute values for macros
infowindow: '<div class=\"infowindow\">Owner: <span style=\"font-weight:bold;\">%owner%</span><br/>Managers: <span style=\"font-weight:bold;\">%managers%</span><br/>Builders: <span style=\"font-weight:bold;\">%builders%</span><br/>Containers: <span style=\"font-weight:bold;\">%containers%</span><br/>Accessors: <span style=\"font-weight:bold;\">%accessors%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  
# Optional list for defining the claims to be shown.  If list is non-empty, only claims matching one of the list strings are shown:
# Values can include '<username>' (claims owned by given user), 'world:<worldid>' (all claims on a specific world),
# '<worldid>/<username>' (claims owned by a given user on a given world)
visibleregions: [ ]
  
# Optional list for restricting the claims shown.  If list is non-empty, any claims matching one of the list strings are not shown:
# Values can include '<username>' (claims owned by given user), 'world:<worldid>' (all claims on a specific world),
# '<worldid>/<username>' (claims owned by a given user on a given world)
hiddenregions: [ ]

# Optional per-owner overrides for regionstyle
ownerstyle:
  kingoftheworld:
    strokeColor: "#C0C0C0"
    
